
var createMtgDraftBots = (function() {
  var _scriptDir = import.meta.url;
  
  return (
function(createMtgDraftBots) {
  createMtgDraftBots = createMtgDraftBots || {};


null;var f;f||(f=typeof createMtgDraftBots !== 'undefined' ? createMtgDraftBots : {});var aa,ba;f.ready=new Promise(function(a,b){aa=a;ba=b});"undefined"===typeof f&&(f={});f.print=function(a){console.log("stdout:",a)};f.printErr=function(a){console.error("stderr:",a)};var r={},t;for(t in f)f.hasOwnProperty(t)&&(r[t]=f[t]);var ca=[],da="./this.program";function ea(a,b){throw b;}var v="",fa;"undefined"!==typeof document&&document.currentScript&&(v=document.currentScript.src);_scriptDir&&(v=_scriptDir);
0!==v.indexOf("blob:")?v=v.substr(0,v.lastIndexOf("/")+1):v="";fa=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var w=f.printErr||console.warn.bind(console);for(t in r)r.hasOwnProperty(t)&&(f[t]=r[t]);r=null;f.arguments&&(ca=f.arguments);f.thisProgram&&(da=f.thisProgram);f.quit&&(ea=f.quit);var y;f.wasmBinary&&(y=f.wasmBinary);
var noExitRuntime=f.noExitRuntime||!0;"object"!==typeof WebAssembly&&A("no native wasm support detected");var ha,B=!1,ia="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function ja(a,b){var c=D,d=a+b;for(b=a;c[b]&&!(b>=d);)++b;if(16<b-a&&c.subarray&&ia)return ia.decode(c.subarray(a,b));for(d="";a<b;){var e=c[a++];if(e&128){var g=c[a++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|g);else{var l=c[a++]&63;e=224==(e&240)?(e&15)<<12|g<<6|l:(e&7)<<18|g<<12|l<<6|c[a++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}
function ka(a,b,c,d){if(0<d){d=c+d-1;for(var e=0;e<a.length;++e){var g=a.charCodeAt(e);if(55296<=g&&57343>=g){var l=a.charCodeAt(++e);g=65536+((g&1023)<<10)|l&1023}if(127>=g){if(c>=d)break;b[c++]=g}else{if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6}else{if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63}b[c++]=128|g>>6&63}b[c++]=128|g&63}}b[c]=0}}
function la(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}var ma="undefined"!==typeof TextDecoder?new TextDecoder("utf-16le"):void 0;function na(a,b){var c=a>>1;for(var d=c+b/2;!(c>=d)&&E[c];)++c;c<<=1;if(32<c-a&&ma)return ma.decode(D.subarray(a,c));c="";for(d=0;!(d>=b/2);++d){var e=F[a+2*d>>1];if(0==e)break;c+=String.fromCharCode(e)}return c}
function oa(a,b,c){void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)F[b>>1]=a.charCodeAt(e),b+=2;F[b>>1]=0;return b-d}function pa(a){return 2*a.length}function qa(a,b){for(var c=0,d="";!(c>=b/4);){var e=G[a+4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d}
function ra(a,b,c){void 0===c&&(c=2147483647);if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var g=a.charCodeAt(e);if(55296<=g&&57343>=g){var l=a.charCodeAt(++e);g=65536+((g&1023)<<10)|l&1023}G[b>>2]=g;b+=4;if(b+4>c)break}G[b>>2]=0;return b-d}function sa(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b}function ta(a){var b=la(a)+1,c=ua(b);ka(a,H,c,b);return c}var va,H,D,F,E,G,J,wa,xa;
function ya(){var a=ha.buffer;va=a;f.HEAP8=H=new Int8Array(a);f.HEAP16=F=new Int16Array(a);f.HEAP32=G=new Int32Array(a);f.HEAPU8=D=new Uint8Array(a);f.HEAPU16=E=new Uint16Array(a);f.HEAPU32=J=new Uint32Array(a);f.HEAPF32=wa=new Float32Array(a);f.HEAPF64=xa=new Float64Array(a)}var K,za=[],Aa=[],Ba=[],Ca=[];function Da(){var a=f.preRun.shift();za.unshift(a)}var L=0,Ea=null,M=null;f.preloadedImages={};f.preloadedAudios={};
function A(a){if(f.onAbort)f.onAbort(a);w(a);B=!0;a=new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");ba(a);throw a;}function Fa(){return N.startsWith("data:application/octet-stream;base64,")}var N;if(f.locateFile){if(N="MtgDraftBotsWasmBrowser.wasm",!Fa()){var Ga=N;N=f.locateFile?f.locateFile(Ga,v):v+Ga}}else N=(new URL("MtgDraftBotsWasmBrowser.wasm",import.meta.url)).toString();
function Ha(){var a=N;try{if(a==N&&y)return new Uint8Array(y);throw"both async and sync fetching of the wasm failed";}catch(b){A(b)}}function Ia(){return y||"function"!==typeof fetch?Promise.resolve().then(function(){return Ha()}):fetch(N,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+N+"'";return a.arrayBuffer()}).catch(function(){return Ha()})}
function Ja(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(f);else{var c=b.na;"number"===typeof c?void 0===b.T?K.get(c)():K.get(c)(b.T):c(void 0===b.T?null:b.T)}}}function Ka(a){this.S=a-16;this.ma=function(b){G[this.S+4>>2]=b};this.ja=function(b){G[this.S+8>>2]=b};this.ka=function(){G[this.S>>2]=0};this.ia=function(){H[this.S+12>>0]=0};this.la=function(){H[this.S+13>>0]=0};this.ga=function(b,c){this.ma(b);this.ja(c);this.ka();this.ia();this.la()}}var La=0,Ma={};
function Na(a){for(;a.length;){var b=a.pop();a.pop()(b)}}function O(a){return this.fromWireType(J[a>>2])}var P={},Q={},Oa={};function Pa(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}function Qa(a,b){a=Pa(a);return(new Function("body","return function "+a+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(b)}
function Ra(a){var b=Error,c=Qa(a,function(d){this.name=a;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}var Sa=void 0;
function Ta(a,b,c){function d(h){h=c(h);if(h.length!==a.length)throw new Sa("Mismatched type converter count");for(var k=0;k<a.length;++k)S(a[k],h[k])}a.forEach(function(h){Oa[h]=b});var e=Array(b.length),g=[],l=0;b.forEach(function(h,k){Q.hasOwnProperty(h)?e[k]=Q[h]:(g.push(h),P.hasOwnProperty(h)||(P[h]=[]),P[h].push(function(){e[k]=Q[h];++l;l===g.length&&d(e)}))});0===g.length&&d(e)}var Ua={};
function Va(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}var Wa=void 0;function T(a){for(var b="";D[a];)b+=Wa[D[a++]];return b}var Xa=void 0;function U(a){throw new Xa(a);}
function S(a,b,c){c=c||{};if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var d=b.name;a||U('type "'+d+'" must have a positive integer typeid pointer');if(Q.hasOwnProperty(a)){if(c.fa)return;U("Cannot register type '"+d+"' twice")}Q[a]=b;delete Oa[a];P.hasOwnProperty(a)&&(b=P[a],delete P[a],b.forEach(function(e){e()}))}var Ya=[],V=[{},{value:void 0},{value:null},{value:!0},{value:!1}];
function Za(a){4<a&&0===--V[a].Z&&(V[a]=void 0,Ya.push(a))}function W(a){switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=Ya.length?Ya.pop():V.length;V[b]={Z:1,value:a};return b}}function $a(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}
function ab(a,b){switch(b){case 2:return function(c){return this.fromWireType(wa[c>>2])};case 3:return function(c){return this.fromWireType(xa[c>>3])};default:throw new TypeError("Unknown float type: "+a);}}function bb(a){var b=Function;if(!(b instanceof Function))throw new TypeError("new_ called with constructor type "+typeof b+" which is not a function");var c=Qa(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
function cb(a,b){var c=f;if(void 0===c[a].R){var d=c[a];c[a]=function(){c[a].R.hasOwnProperty(arguments.length)||U("Function '"+b+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+c[a].R+")!");return c[a].R[arguments.length].apply(this,arguments)};c[a].R=[];c[a].R[d.da]=d}}
function db(a,b,c){f.hasOwnProperty(a)?((void 0===c||void 0!==f[a].R&&void 0!==f[a].R[c])&&U("Cannot register public name '"+a+"' twice"),cb(a,a),f.hasOwnProperty(c)&&U("Cannot register multiple overloads of a function with the same number of arguments ("+c+")!"),f[a].R[c]=b):(f[a]=b,void 0!==c&&(f[a].oa=c))}function eb(a,b){for(var c=[],d=0;d<a;d++)c.push(G[(b>>2)+d]);return c}
function fb(a,b){var c=[];return function(){c.length=arguments.length;for(var d=0;d<arguments.length;d++)c[d]=arguments[d];a.includes("j")?(d=f["dynCall_"+a],d=c&&c.length?d.apply(null,[b].concat(c)):d.call(null,b)):d=K.get(b).apply(null,c);return d}}function X(a,b){a=T(a);var c=a.includes("j")?fb(a,b):K.get(b);"function"!==typeof c&&U("unknown function pointer with signature "+a+": "+b);return c}var gb=void 0;function hb(a){a=ib(a);var b=T(a);Y(a);return b}
function jb(a,b){function c(g){e[g]||Q[g]||(Oa[g]?Oa[g].forEach(c):(d.push(g),e[g]=!0))}var d=[],e={};b.forEach(c);throw new gb(a+": "+d.map(hb).join([", "]));}function kb(a,b,c){switch(b){case 0:return c?function(d){return H[d]}:function(d){return D[d]};case 1:return c?function(d){return F[d>>1]}:function(d){return E[d>>1]};case 2:return c?function(d){return G[d>>2]}:function(d){return J[d>>2]};default:throw new TypeError("Unknown integer type: "+a);}}
function lb(a){a||U("Cannot use deleted val. handle = "+a);return V[a].value}function mb(a,b){var c=Q[a];void 0===c&&U(b+" has unknown type "+hb(a));return c}var nb={};function ob(a){var b=nb[a];return void 0===b?T(a):b}var pb=[];function qb(a){var b=pb.length;pb.push(a);return b}function rb(a,b){for(var c=Array(a),d=0;d<a;++d)c[d]=mb(G[(b>>2)+d],"parameter "+d);return c}
function sb(a,b,c){fa(a,function(d){d||A('Assertion failed: Loading data file "'+(a+'" failed (no arrayBuffer).'));b(new Uint8Array(d))},function(){if(c)c();else throw'Loading data file "'+a+'" failed.';})}function tb(a){if(!B)try{a()}catch(b){if(!(b instanceof ub)&&"unwind"!==b)throw b&&"object"===typeof b&&b.stack&&w("exception thrown: "+[b,b.stack]),b;}}Sa=f.InternalError=Ra("InternalError");for(var vb=Array(256),wb=0;256>wb;++wb)vb[wb]=String.fromCharCode(wb);Wa=vb;Xa=f.BindingError=Ra("BindingError");
f.count_emval_handles=function(){for(var a=0,b=5;b<V.length;++b)void 0!==V[b]&&++a;return a};f.get_first_emval=function(){for(var a=5;a<V.length;++a)if(void 0!==V[a])return V[a];return null};gb=f.UnboundTypeError=Ra("UnboundTypeError");
var xb={x:function(a){return Z(a+16)+16},u:function(a,b,c){(new Ka(a)).ga(b,c);La++;throw a;},v:function(a){var b=Ma[a];delete Ma[a];var c=b.elements,d=c.length,e=c.map(function(h){return h.W}).concat(c.map(function(h){return h.aa})),g=b.X,l=b.Y;Ta([a],e,function(h){c.forEach(function(k,m){var n=h[m],q=k.U,x=k.V,z=h[m+d],p=k.$,R=k.ba;k.read=function(u){return n.fromWireType(q(x,u))};k.write=function(u,C){var I=[];p(R,u,z.toWireType(I,C));Na(I)}});return[{name:b.name,fromWireType:function(k){for(var m=
Array(d),n=0;n<d;++n)m[n]=c[n].read(k);l(k);return m},toWireType:function(k,m){if(d!==m.length)throw new TypeError("Incorrect number of tuple elements for "+b.name+": expected="+d+", actual="+m.length);for(var n=g(),q=0;q<d;++q)c[q].write(n,m[q]);null!==k&&k.push(l,n);return n},argPackAdvance:8,readValueFromPointer:O,P:l}]})},o:function(a){var b=Ua[a];delete Ua[a];var c=b.X,d=b.Y,e=b.ca,g=e.map(function(l){return l.W}).concat(e.map(function(l){return l.aa}));Ta([a],g,function(l){var h={};e.forEach(function(k,
m){var n=l[m],q=k.U,x=k.V,z=l[m+e.length],p=k.$,R=k.ba;h[k.ea]={read:function(u){return n.fromWireType(q(x,u))},write:function(u,C){var I=[];p(R,u,z.toWireType(I,C));Na(I)}}});return[{name:b.name,fromWireType:function(k){var m={},n;for(n in h)m[n]=h[n].read(k);d(k);return m},toWireType:function(k,m){for(var n in h)if(!(n in m))throw new TypeError('Missing field:  "'+n+'"');var q=c();for(n in h)h[n].write(q,m[n]);null!==k&&k.push(d,q);return q},argPackAdvance:8,readValueFromPointer:O,P:d}]})},y:function(){},
C:function(a,b,c,d,e){var g=Va(c);b=T(b);S(a,{name:b,fromWireType:function(l){return!!l},toWireType:function(l,h){return h?d:e},argPackAdvance:8,readValueFromPointer:function(l){if(1===c)var h=H;else if(2===c)h=F;else if(4===c)h=G;else throw new TypeError("Unknown boolean type size: "+b);return this.fromWireType(h[l>>g])},P:null})},B:function(a,b){b=T(b);S(a,{name:b,fromWireType:function(c){var d=V[c].value;Za(c);return d},toWireType:function(c,d){return W(d)},argPackAdvance:8,readValueFromPointer:O,
P:null})},s:function(a,b,c){c=Va(c);b=T(b);S(a,{name:b,fromWireType:function(d){return d},toWireType:function(d,e){if("number"!==typeof e&&"boolean"!==typeof e)throw new TypeError('Cannot convert "'+$a(e)+'" to '+this.name);return e},argPackAdvance:8,readValueFromPointer:ab(b,c),P:null})},E:function(a,b,c,d,e,g){var l=eb(b,c);a=T(a);e=X(d,e);db(a,function(){jb("Cannot call "+a+" due to unbound types",l)},b-1);Ta([],l,function(h){var k=a,m=a;h=[h[0],null].concat(h.slice(1));var n=e,q=h.length;2>q&&
U("argTypes array size mismatch! Must at least get return value and 'this' types!");for(var x=null!==h[1]&&!1,z=!1,p=1;p<h.length;++p)if(null!==h[p]&&void 0===h[p].P){z=!0;break}var R="void"!==h[0].name,u="",C="";for(p=0;p<q-2;++p)u+=(0!==p?", ":"")+"arg"+p,C+=(0!==p?", ":"")+"arg"+p+"Wired";m="return function "+Pa(m)+"("+u+") {\nif (arguments.length !== "+(q-2)+") {\nthrowBindingError('function "+m+" called with ' + arguments.length + ' arguments, expected "+(q-2)+" args!');\n}\n";z&&(m+="var destructors = [];\n");
var I=z?"destructors":"null";u="throwBindingError invoker fn runDestructors retType classParam".split(" ");n=[U,n,g,Na,h[0],h[1]];x&&(m+="var thisWired = classParam.toWireType("+I+", this);\n");for(p=0;p<q-2;++p)m+="var arg"+p+"Wired = argType"+p+".toWireType("+I+", arg"+p+"); // "+h[p+2].name+"\n",u.push("argType"+p),n.push(h[p+2]);x&&(C="thisWired"+(0<C.length?", ":"")+C);m+=(R?"var rv = ":"")+"invoker(fn"+(0<C.length?", ":"")+C+");\n";if(z)m+="runDestructors(destructors);\n";else for(p=x?1:2;p<
h.length;++p)q=1===p?"thisWired":"arg"+(p-2)+"Wired",null!==h[p].P&&(m+=q+"_dtor("+q+"); // "+h[p].name+"\n",u.push(q+"_dtor"),n.push(h[p].P));R&&(m+="var ret = retType.fromWireType(rv);\nreturn ret;\n");u.push(m+"}\n");h=bb(u).apply(null,n);p=b-1;if(!f.hasOwnProperty(k))throw new Sa("Replacing nonexistant public symbol");void 0!==f[k].R&&void 0!==p?f[k].R[p]=h:(f[k]=h,f[k].da=p);return[]})},h:function(a,b,c,d,e){function g(m){return m}b=T(b);-1===e&&(e=4294967295);var l=Va(c);if(0===d){var h=32-
8*c;g=function(m){return m<<h>>>h}}var k=b.includes("unsigned");S(a,{name:b,fromWireType:g,toWireType:function(m,n){if("number"!==typeof n&&"boolean"!==typeof n)throw new TypeError('Cannot convert "'+$a(n)+'" to '+this.name);if(n<d||n>e)throw new TypeError('Passing a number "'+$a(n)+'" from JS side to C/C++ side to an argument of type "'+b+'", which is outside the valid range ['+d+", "+e+"]!");return k?n>>>0:n|0},argPackAdvance:8,readValueFromPointer:kb(b,l,0!==d),P:null})},d:function(a,b,c){function d(g){g>>=
2;var l=J;return new e(va,l[g+1],l[g])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=T(c);S(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{fa:!0})},t:function(a,b){b=T(b);var c="std::string"===b;S(a,{name:b,fromWireType:function(d){var e=J[d>>2];if(c)for(var g=d+4,l=0;l<=e;++l){var h=d+4+l;if(l==e||0==D[h]){g=g?ja(g,h-g):"";if(void 0===k)var k=g;else k+=String.fromCharCode(0),k+=g;g=h+1}}else{k=Array(e);for(l=0;l<e;++l)k[l]=
String.fromCharCode(D[d+4+l]);k=k.join("")}Y(d);return k},toWireType:function(d,e){e instanceof ArrayBuffer&&(e=new Uint8Array(e));var g="string"===typeof e;g||e instanceof Uint8Array||e instanceof Uint8ClampedArray||e instanceof Int8Array||U("Cannot pass non-string to std::string");var l=(c&&g?function(){return la(e)}:function(){return e.length})(),h=Z(4+l+1);J[h>>2]=l;if(c&&g)ka(e,D,h+4,l+1);else if(g)for(g=0;g<l;++g){var k=e.charCodeAt(g);255<k&&(Y(h),U("String has UTF-16 code units that do not fit in 8 bits"));
D[h+4+g]=k}else for(g=0;g<l;++g)D[h+4+g]=e[g];null!==d&&d.push(Y,h);return h},argPackAdvance:8,readValueFromPointer:O,P:function(d){Y(d)}})},r:function(a,b,c){c=T(c);if(2===b){var d=na;var e=oa;var g=pa;var l=function(){return E};var h=1}else 4===b&&(d=qa,e=ra,g=sa,l=function(){return J},h=2);S(a,{name:c,fromWireType:function(k){for(var m=J[k>>2],n=l(),q,x=k+4,z=0;z<=m;++z){var p=k+4+z*b;if(z==m||0==n[p>>h])x=d(x,p-x),void 0===q?q=x:(q+=String.fromCharCode(0),q+=x),x=p+b}Y(k);return q},toWireType:function(k,
m){"string"!==typeof m&&U("Cannot pass non-string to C++ string type "+c);var n=g(m),q=Z(4+n+b);J[q>>2]=n>>h;e(m,q+4,n+b);null!==k&&k.push(Y,q);return q},argPackAdvance:8,readValueFromPointer:O,P:function(k){Y(k)}})},w:function(a,b,c,d,e,g){Ma[a]={name:T(b),X:X(c,d),Y:X(e,g),elements:[]}},a:function(a,b,c,d,e,g,l,h,k){Ma[a].elements.push({W:b,U:X(c,d),V:e,aa:g,$:X(l,h),ba:k})},p:function(a,b,c,d,e,g){Ua[a]={name:T(b),X:X(c,d),Y:X(e,g),ca:[]}},c:function(a,b,c,d,e,g,l,h,k,m){Ua[a].ca.push({ea:T(b),
W:c,U:X(d,e),V:g,aa:l,$:X(h,k),ba:m})},D:function(a,b){b=T(b);S(a,{ha:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},f:function(a,b,c){a=lb(a);b=mb(b,"emval::as");var d=[],e=W(d);G[c>>2]=e;return b.toWireType(d,a)},j:function(a,b,c,d){a=pb[a];b=lb(b);c=ob(c);a(b,c,null,d)},b:Za,i:function(a,b){b=rb(a,b);for(var c=b[0],d=c.name+"_$"+b.slice(1).map(function(m){return m.name}).join("_")+"$",e=["retType"],g=[c],l="",h=0;h<a-1;++h)l+=(0!==h?", ":"")+"arg"+h,e.push("argType"+
h),g.push(b[1+h]);d="return function "+Pa("methodCaller_"+d)+"(handle, name, destructors, args) {\n";var k=0;for(h=0;h<a-1;++h)d+="    var arg"+h+" = argType"+h+".readValueFromPointer(args"+(k?"+"+k:"")+");\n",k+=b[h+1].argPackAdvance;d+="    var rv = handle[name]("+l+");\n";for(h=0;h<a-1;++h)b[h+1].deleteObject&&(d+="    argType"+h+".deleteObject(arg"+h+");\n");c.ha||(d+="    return retType.toWireType(destructors, rv);\n");e.push(d+"};\n");a=bb(e).apply(null,g);return qb(a)},g:function(a,b){a=lb(a);
b=lb(b);return W(a[b])},l:function(a){4<a&&(V[a].Z+=1)},k:function(){return W([])},n:function(a){return W(ob(a))},e:function(a){Na(V[a].value);Za(a)},m:function(a,b){a=mb(a,"_emval_take_value");a=a.readValueFromPointer(b);return W(a)},A:function(){A()},F:function(a,b,c,d){sb(a?ja(a,void 0):"",function(e){tb(function(){var g=Z(e.length);D.set(e,g);K.get(c)(b,g,e.length);Y(g)})},function(){d&&tb(function(){K.get(d)(b)})})},z:function(a,b,c){D.copyWithin(a,b,b+c)},q:function(a){var b=D.length;a>>>=0;
if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);d=Math.max(a,d);0<d%65536&&(d+=65536-d%65536);a:{try{ha.grow(Math.min(2147483648,d)-va.byteLength+65535>>>16);ya();var e=1;break a}catch(g){}e=void 0}if(e)return!0}return!1}};
(function(){function a(e){f.asm=e.exports;ha=f.asm.G;ya();K=f.asm.O;Aa.unshift(f.asm.H);L--;f.monitorRunDependencies&&f.monitorRunDependencies(L);0==L&&(null!==Ea&&(clearInterval(Ea),Ea=null),M&&(e=M,M=null,e()))}function b(e){a(e.instance)}function c(e){return Ia().then(function(g){return WebAssembly.instantiate(g,d)}).then(e,function(g){w("failed to asynchronously prepare wasm: "+g);A(g)})}var d={a:xb};L++;f.monitorRunDependencies&&f.monitorRunDependencies(L);if(f.instantiateWasm)try{return f.instantiateWasm(d,
a)}catch(e){return w("Module.instantiateWasm callback failed with error: "+e),!1}(function(){return y||"function"!==typeof WebAssembly.instantiateStreaming||Fa()||"function"!==typeof fetch?c(b):fetch(N,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(b,function(g){w("wasm streaming compile failed: "+g);w("falling back to ArrayBuffer instantiation");return c(b)})})})().catch(ba);return{}})();
f.___wasm_call_ctors=function(){return(f.___wasm_call_ctors=f.asm.H).apply(null,arguments)};f._main=function(){return(f._main=f.asm.I).apply(null,arguments)};var Z=f._malloc=function(){return(Z=f._malloc=f.asm.J).apply(null,arguments)},ib=f.___getTypeName=function(){return(ib=f.___getTypeName=f.asm.K).apply(null,arguments)};f.___embind_register_native_and_builtin_types=function(){return(f.___embind_register_native_and_builtin_types=f.asm.L).apply(null,arguments)};
var ua=f.stackAlloc=function(){return(ua=f.stackAlloc=f.asm.M).apply(null,arguments)},Y=f._free=function(){return(Y=f._free=f.asm.N).apply(null,arguments)},yb;function ub(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}M=function zb(){yb||Ab();yb||(M=zb)};
function Ab(a){function b(){if(!yb&&(yb=!0,f.calledRun=!0,!B)){Ja(Aa);Ja(Ba);aa(f);if(f.onRuntimeInitialized)f.onRuntimeInitialized();if(Bb){var c=a,d=f._main;c=c||[];var e=c.length+1,g=ua(4*(e+1));G[g>>2]=ta(da);for(var l=1;l<e;l++)G[(g>>2)+l]=ta(c[l-1]);G[(g>>2)+e]=0;try{var h=d(e,g);if(!noExitRuntime){if(f.onExit)f.onExit(h);B=!0}ea(h,new ub(h))}catch(k){k instanceof ub||"unwind"==k||((c=k)&&"object"===typeof k&&k.stack&&(c=[k,k.stack]),w("exception thrown: "+c),ea(1,k))}finally{}}if(f.postRun)for("function"==
typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;)c=f.postRun.shift(),Ca.unshift(c);Ja(Ca)}}a=a||ca;if(!(0<L)){if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)Da();Ja(za);0<L||(f.setStatus?(f.setStatus("Running..."),setTimeout(function(){setTimeout(function(){f.setStatus("")},1);b()},1)):b())}}f.run=Ab;if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();var Bb=!0;f.noInitialRun&&(Bb=!1);Ab();


  return createMtgDraftBots.ready
}
);
})();
export default createMtgDraftBots;